### ISSUE TITLE
Pipfile error

### ISSUE THREAD

**Issue by sashman-jaspin** [interlay/collateralization-analysis#10]
pipenv is throwing this error when trying to read the Pipfile  : 

Versions
Python 3.8.10
pipenv 2022.11.23
pip 20.0.2 (python 3.8)

Command
pipenv check or pipenv install

Traceback (most recent call last):
  File "/home/sas-gs/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 239, in install
    do_install(
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/core.py", line 2132, in do_install
    ensure_project(
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/core.py", line 538, in ensure_project
    ensure_virtualenv(
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/core.py", line 459, in ensure_virtualenv
    python = ensure_python(project, three=three, python=python)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/core.py", line 344, in ensure_python
    python = project.required_python_version
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/project.py", line 193, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get("python_full_version")
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/project.py", line 489, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/project.py", line 515, in _parse_pipfile
    return toml.loads(contents)
  File "/home/sas-gs/.local/lib/python3.8/site-packages/pipenv/vendor/toml/decoder.py", line 260, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
pipenv.vendor.toml.decoder.TomlDecodeError: Found invalid character in key name: '>'. Try quoting the key name. (line 20 column 16 char 260)

**Comment by sashman-jaspin** [comment]
Was able to fix this by removing virtualenv and reinstalling it with pip.

apt remove python3-virtualenv
pip install --user virtualenv --force-reinstall
